FROM python:3.9-slim

WORKDIR /app

# 필수 라이브러리 설치
COPY requirements_hub.txt .
RUN pip install --no-cache-dir -r requirements_hub.txt

# 소스 코드 복사
COPY hub_server.py .

# Flask-SocketIO 기본 포트
EXPOSE 5000

# 서버 실행 (Eventlet 모드)
CMD ["python", "-u", "hub_server.py"]