apiVersion: v1
kind: Pod
metadata:
  name: task-worker-temp
  labels:
    role: mission-worker
spec:
  # 1. 로봇 통신을 위해 호스트 네트워크 유지
  hostNetwork: true
  
  # 2. [핵심 수정] 호스트 네트워크 사용 시에도 K8s DNS(CoreDNS)를 사용하도록 설정
  # 이 설정이 없으면 'redis-service'라는 이름을 못 찾아서 에러가 납니다.
  dnsPolicy: ClusterFirstWithHostNet

  nodeSelector:
    kubernetes.io/hostname: pi1 
    
  restartPolicy: Never
  
  containers:
  - name: worker-container
    image: "PENDING"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
    env:
    - name: REDIS_HOST
      # 3. [보완] 더 명확한 주소인 FQDN 형식을 사용합니다.
      value: "redis-service.default.svc.cluster.local"
    - name: ROBOT_SN
      value: "PENDING"
    - name: TASK_ID
      value: "PENDING"